[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "ui"
path = "src/main.rs"

[dependencies]
yew = { version = "0.20", features = ["csr"] }
yew-router = "0.17"
serde = { version = "1.0", features = ["derive"] }
gloo-net = "0.2"
wasm-bindgen = "0.2"